python ASTAR-Trasaldos.py ./ASTAR-tests/mapa.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa.csv 2
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa2.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa2.csv 2
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa3.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa3.csv 2
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa4.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa4.csv 2
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa5.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa5.csv 2
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa6.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa6.csv 2
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa7.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa7.csv 2
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa8.csv 1
python ASTAR-Trasaldos.py ./ASTAR-tests/mapa8.csv 2